version: '3.9'
services:
    nextjs:
        platform: linux/arm64/v8
        restart: always
        image: loganlee/liz-web-next-js:latest
        container_name: liz-web
        build: ./
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '1.00'
        #             memory: 800M
        #         reservations:
        #             cpus: '0.25'
        #             memory: 128M
    nginx:
        restart: always
        platform: linux/arm64/v8
        image: loganlee/liz-web-nginx:latest
        container_name: nginx
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - nextjs
