import { Grid, Text } from '@nextui-org/react';
import { getRecentAccessLogQuery } from 'lib/log';
import type { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { getSelectorsByUserAgent } from 'react-device-detect';
import styled from 'styled-components';

type Props = {
	isMobile: boolean;
};
// const MobileContainer = dynamic(() => import('containers/page/MobileContainer'), {});
// const DesktopContainer = dynamic(() => import('containers/page/DesktopContainer'), {});

const Freelancer = ({ isMobile = true }: Props) => {
	return (
		<>
			<Wrapper>
				<Head>
					<title>Seize what you want without NO LIMIT.</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
					<meta name='viewport' content='initial-scale=1, width=device-width' />
				</Head>
				<main tabIndex={0}>
					<Grid.Container justify='center' className='container'>
						<Grid>
							<Text>준비 중 입니다.</Text>
						</Grid>
					</Grid.Container>
				</main>
			</Wrapper>
			{/* {isValidating && <CustomLoading />} */}
		</>
	);
};

const Wrapper = styled.div`
	/* min-height: 100vh; */
	/* .container { */
	/* height: 30vh; */
	/* } */
`;

export default Freelancer;

export async function getServerSideProps({ req, res }: GetServerSidePropsContext) {
	const userAgent = req.headers['user-agent'] || '';

	const detect = getSelectorsByUserAgent(userAgent);

	const recentAccessLog = await getRecentAccessLogQuery();

	return {
		props: {
			isMobile: detect?.isMobile,
			recentAccessLog: JSON.parse(JSON.stringify(recentAccessLog)),
		},
	};
}
