import { GetServerSidePropsContext } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { getSelectorsByUserAgent } from 'react-device-detect';
import styled from 'styled-components';

const MobileContainer = dynamic(() => import('containers/page/template/MobileContainer'), {});
const DesktopContainer = dynamic(() => import('containers/page/template/DesktopContainer'), {});

type Props = {
	isMobile: boolean;
};
const Template = ({ isMobile, ...props }: Props) => {
	return (
		<Wrapper>
			<Head>
				<title>Seize what you want without NO LIMIT.</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<meta name='viewport' content='initial-scale=1, width=device-width' />
			</Head>
			<main>
				{isMobile && <MobileContainer {...props} />}
				{!isMobile && <DesktopContainer {...props} />}
			</main>
		</Wrapper>
	);
};
const Wrapper = styled.div``;

export async function getServerSideProps({ req, res }: GetServerSidePropsContext) {
	const userAgent = req.headers['user-agent'] || '';

	const detect = getSelectorsByUserAgent(userAgent);

	return {
		props: { isMobile: detect?.isMobile }, // will be passed to the page component as props
	};
}
export default Template;
